# Generated by Django 6.0.2 on 2026-03-12 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblio',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('isbn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('is_available', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': '書誌情報',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': '階情報',
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shelf', to='books.floor')),
            ],
            options={
                'verbose_name_plural': '本棚情報',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('is_abavailable', models.BooleanField(default=True)),
                ('biblio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='books.biblio')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book', to='books.shelf')),
            ],
            options={
                'verbose_name_plural': '書籍',
            },
        ),
    ]
