# Generated by Django 6.0.2 on 2026-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='price',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
