# Generated by Django 6.0.2 on 2026-03-13 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='is_abavailable',
            new_name='is_available',
        ),
    ]
