# Generated by Django 6.0.2 on 2026-03-31 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_is_abavailable_book_is_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': '蔵書情報'},
        ),
        migrations.AlterField(
            model_name='book',
            name='count',
            field=models.IntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('biblio', 'count')},
        ),
    ]
