# Generated by Django 6.0.2 on 2026-04-27 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_biblio_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biblio',
            name='price',
        ),
    ]
