# Generated by Django 6.0.2 on 2026-05-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_remove_biblio_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblio',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
        migrations.AddField(
            model_name='biblio',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
        migrations.AddField(
            model_name='book',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='floor',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
        migrations.AddField(
            model_name='floor',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='有効フラグ'),
        ),
        migrations.AddField(
            model_name='shelf',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='biblio',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='biblio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='book',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='shelf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
    ]
